### ISSUE TITLE
Better error reporting when loading malformed styles

### ISSUE THREAD

**Issue by almccon** [stamen/maperture#107]
When maperture can't load a style json because it's got a syntax error, we get an "Error: Style was not found" message in the layer picker, but on the console I can see it was actually a syntax error. In my case: `main.js:8 SyntaxError: Expected ',' or '}' after property value in JSON at position 88582`

Possible improvements:
1. could we detect the difference between a missing or inaccessible file (which would get the "Style was not found" error) versus a file that is an unparseable style (which would get something like "Style syntax error" or "Style file could not be parsed" message)?
2. I also notice that a parsing error in one of the local styles caused all of my local styles to disappear from the picker. Is it possible to have the picker maintain the parsable styles, and maybe indicate if one of the local styles has an error (maybe strikethrough the name of the style in the picker?)

**Comment by aparlato** [comment]
> I also notice that a parsing error in one of the local styles caused all of my local styles to disappear from the picker. Is it possible to have the picker maintain the parsable styles, and maybe indicate if one of the local styles has an error (maybe strikethrough the name of the style in the picker?)

@almccon https://github.com/stamen/maperture/pull/117 should provide better error messages, but for this issue, my guess would be this is happening due to a setup step in the `local.js` file of your client repo rather than in `maperture` code. Without seeing the specific implementation, can you tell me if there is there logic in there that looks like:
```js
let localServerIsRunning = false;
const localUrlPath = 'http://localhost:8000/styles';

try {
  const response = await fetch(`${localUrlPath}/cool-style/style.json`);
  const style = await response.json();
  if (style) {
    localServerIsRunning = true;
  }
} catch (err) {}
```
I know this logic has been a problem elsewhere (I've unfortunately written this logic in places), so if this is what it looks like, then erroring on that one style may cause logic further down in `local.js` to determine that no local styles should be available.

Instead we would want to implement something like:
```js
const localServerIsRunning = window.location.origin.includes('localhost');
```

If this doesn't appear to be the problem, then maybe we can open a ticket in the client repo for me to see the implementation this is a problem with and we can open a new upstream ticket here if necessary.
