### ISSUE TITLE
History updates are hardcoded to `/`.  Should use Window `origin` & `pathname`

### ISSUE THREAD

**Issue by roblabs** [stamen/maperture#139]
Related to changes in #132 where the URL history is managed to only keep certain history items.

---

When updating the history, the Window origin is hard coded via Line 143 (below) to `/`. This breaks functionality on our fork for open source & public domain (Atlas) maps.      See step # 5 below for live demonstration of the issue, but the video is intended to show the issue as well.

https://github.com/stamen/maperture/blob/202600260d5b51fde105fb6757c2e28d7b69b866/src/query.js#L143

---

### Steps to Reproduce

1.  Navigate to http://localhost:5000.  Mapbox demo. Works.  See video time (0, 4) seconds.
2. Manually change the URL to http://localhost:5000/open-source.  MapLibre demo. Works.  See video time (4, 14) seconds.
3. When changing the zoom, the `window.location` is replaced with `${'process.env.BASE_PATH'}#${nextHash}`.      See video time at 14 seconds, you'll see that the zoom changes, but also the proper URL is over written.  The URL was `/open-source`, but it is now `/`.  Now the URL is broken and cannot be shared.
4. Issue is that `process.env.BASE_PATH` is hardcoded to `/`.
5. You can also see this issue live at:  https://roblabs.com/maperture/open-source, which is our fork and `gh-pages` in action for this excellent tool.
6. We have some tests around using something like this, but wanted your ideas first
 
```JavaScript
window.location.replace(window.location.origin + window.location.pathname + `#${nextHash}`);
```

*Video showing Window origin & pathname changing when customer changes zoom*. This does not allow for copy & paste of the URL.

https://user-images.githubusercontent.com/118112/210624491-29c33e8a-7924-4eeb-8484-317ab3896b0a.mov

**Comment by roblabs** [comment]
Proposed fix to include `origin` & `pathname`.

https://github.com/roblabs/maperture/blob/7503f0539d9d019670898a9cefdb1e5f86754067/src/query.js#L143-L145

**Comment by aparlato** [comment]
@roblabs I see what you mean. The pattern we were following here is to [specify the `BASE_PATH` env variable when you build before deployment based on your implementation](https://github.com/stamen/maperture#building-and-running-in-production-mode) so that it would carry that information, but it's assumed you only have one entry HTML file. So if that was your only entry file your deploy would be something like `BASE_PATH=/open-source/ yarn build &&...` to resolve this.

That said, I can see this doesn't work with the implementation you have creating other HTML entry files to the same built code with different configs. I'm not necessarily against using `origin` and `pathname` here, but it seems like you might run into other issues around `BASE_NAME` as well. @ebrelsford what are your thoughts here on a path forward? If we correct this, are there other issues we might expect around this env variable?

**Comment by roblabs** [comment]
@aparlato  — thanks for the review & for pointing out the `BASE_PATH` notes.  As of now, I have three demos of Maperture that we are using.  (This is how useful Maperture is;  I haven't even started with Leaflet maps)

1. https://RobLabs.com/maperture — the original with Mapbox
2. https://RobLabs.com/maperture/atlas — Public Domain maps
3. https://RobLabs.com/maperture/open-source — MapLibre and various other styles

**Comment by ebrelsford** [comment]
I'm open to this change.

When it comes to `BASE_PATH` it's worth noting that we set the [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element to this value, so relative URLs are relative to this URL. So it's worth setting `BASE_PATH` either way.

Here we set the `<base>` element:

https://github.com/roblabs/maperture/blob/7503f0539d9d019670898a9cefdb1e5f86754067/src/App.svelte#L181-L183
