### ISSUE TITLE
Does Maperture default to MapLibre?

### ISSUE THREAD

**Issue by kelsey-taylor** [stamen/maperture#148]
I'm taking a pass at #147 and #146 and am noticing attribution watermarks for some styles and not others. The one that caught my eye is Mapbox's Streets style, which has a MapLibre watermark:

![Screenshot 2023-01-18 at 11 35 02 AM](https://user-images.githubusercontent.com/57634568/213239828-f5b46758-9942-4bc2-abf9-3759fa68b268.png)

I couldn't tell with a quick glance whether MapLibre is the default, but this one definitely seems wrong. Not sure what the default _should_ be, though, if that is the case here.

**Comment by ebrelsford** [comment]
Hm this is a good point! It should be using Mapbox GL for these styles and only loading Maplibre as needed. Either way this should be more clear.

**Comment by ebrelsford** [comment]
@kelsey-taylor To answer the question here: Maperture does not default to Maplibre. However, because of the way the CSS is bundled the Maplibre CSS overrides the Mapbox CSS and they use the same classes for many elements, so Maplibre styles end up dominating.

I'm going to open up a follow-up issue. We clearly at least need to make sure the logo is correct or remove it since this is going to be confusing.
